Name :- Nikhil Gopale

Student ID :- 44712

Roll No :- 30

Class :- Msc-Data Science And Big Data Analytics.
    
Subject   :-  Data Science With Python

## Numpy Exercise 

### Part 1

#### 1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np

In [2]:
n1 = [1,2,3,4,5,6,7,8,9,10]
np.array(n1)
n1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### 2. Create a 3×3 numpy array of all True’s

In [3]:
n2 = np.full((3,3),'True')
n2

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

#### 3. Extract all odd numbers from 1D array of numbers from 0 to 9

In [4]:
n1 = np.array([0,1,2,3,4,5,6,7,8,9])
n1[n1 % 2 == 1]


array([1, 3, 5, 7, 9])

#### 4. Replace all odd numbers from 1D array of numbers from 0 to 9 with -1 Input


In [5]:
n = int(input("enter no: "))
n1 = np.array([0,1,2,3,4,5,6,7,8,9])
n1[n1%2 == 1] = n 
n1


enter no: -1


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 5. Replace all odd numbers in arr with -1 without changing the array elements

In [6]:
n1 = np.array([0,1,2,3,4,5,6,7,8,9])
n1[n1%2 == 1] = -1
n1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 6. Convert a 1D array to a 2D array with 2 rows Input

In [7]:
n1 = np.array([0,1,2,3,4,5,6,7,8,9])
np.reshape(n1,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 7. Stack arrays a and b vertically and then horizontally  a = np.arange(10).reshape(2,-1)  b = np.repeat(1, 10).reshape(2,-1)



In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

# Vertically array
print(' Vertically array')
print( np.vstack((a,b)))


# horizontally array
print(' horizontally array')
print(np.hstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
 Vertically array
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 horizontally array
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### 8. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. 
Input: a = np.array([1,2,3])
Desired Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### 9. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

# Find Common Value
print(" Common items ")
np.intersect1d(a,b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
 Common items 


array([2, 4])

#### 10. From array a remove all items present in array b (ref array above)

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.setdiff1d(a,b)

array([1, 3, 5, 6])

#### 11. Get the positions where elements of a and b match

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

#### 12. Get all items between 5 and 10 from a.

In [13]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[5:10]

array([ 6,  7,  8,  9, 10])

#### 13. Swap columns 1 and 2 in the array arr = np.arange(9).reshape(3,3)


In [14]:
arr = np.arange(9).reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 14. Swap rows 1 and 2 in the above given array

In [15]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 15. Reverse the rows of above given 2D array

In [16]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 16. Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10.


In [17]:
dec =np.random.uniform(5,10, size=(5,3))
dec

array([[7.62523785, 6.0396964 , 9.43597759],
       [9.08878308, 5.0453041 , 9.93145244],
       [5.61469071, 6.62579493, 8.42159166],
       [6.42318442, 9.38313261, 5.42867537],
       [6.91338755, 5.84743034, 5.01269859]])

#### 17. Limit the number of items printed in python numpy array ‘a’ to a maximum of 6 elements.
 
a= np.arange(15)


In [18]:

np.set_printoptions(threshold=6)
a= np.arange(15)
a


array([ 0,  1,  2, ..., 12, 13, 14])

## Part - 2

#### 1. Import the botany dataset and display the values

In [19]:
# load csv file 
bot = np.genfromtxt('botany.csv', delimiter=',', dtype=None)
bot

C:\Users\USER\AppData\Local\Temp\ipykernel_9536\2100392100.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  bot = np.genfromtxt('botany.csv', delimiter=',', dtype=None)


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , b'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, b'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, b'Iris-virginica')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

#### 2. Extract the text column species from the 1D botany dataset

In [20]:
txt = np.array([row[4] for row in bot])
txt

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S15')

#### 3. Convert the 1D botany to 2D array botany_2d by omitting the species text field


In [21]:
np.array([row.tolist()[:4] for row in bot])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

#### 4. Find the mean, median, standard deviation of botany’s sepallength (1st column)


In [22]:
bot_1 = np.genfromtxt('botany.csv', delimiter=',', dtype=float, usecols=[0])
bot_1

mean=np.mean(bot_1)
print('Mean :',mean)

median=np.median(bot_1)
print('Median :' ,median)

std=np.std(bot_1)
print('std:',std)

Mean : 5.843333333333334
Median : 5.8
std: 0.8253012917851409


#### 5. Find the 5th and 95th percentile of botany’s sepallength

In [23]:
np.percentile(bot_1, q=[5, 95])

array([4.6  , 7.255])

#### 6. Find the number and position of missing values

In [24]:
bot1 = np.genfromtxt('botany.csv', delimiter=',', dtype=float, usecols=[0,1,2,3])
bot1

n=np.isnan(bot1[:, 0]).sum()
n

0

#### 7. Filter the rows of botany_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


In [25]:
con = (bot1[:, 2]>1.5) & (bot1[:, 0]<5.0)

print(bot1[con])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


#### 8. Find out if botany_2d has any missing values.

In [40]:
botany_2d = np.genfromtxt('botany.csv', delimiter=',', dtype=float, usecols=[0,1,2,3])
botany_2d

n=np.isnan(bot1[:, 0]).sum()
n

0

#### 9. Replace all occurrences of nan with ‘0’ in numpy array


In [27]:
array = np.array([[13, np.nan, 16,np.nan], [17, np.NaN, 14,np.nan]])
print(" original array:",array)
new_value = np.nan_to_num(array)
print("Replace nan with zero:",new_value)

 original array: [[13. nan 16. nan]
 [17. nan 14. nan]]
Replace nan with zero: [[13.  0. 16.  0.]
 [17.  0. 14.  0.]]


#### 10. Bin the petal length (3rd) column of botany_2d to form a text array, 
such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [36]:
import numpy as np
bin_petal = np.digitize(botany_2d[:, 2].astype('float'), [0, 3, 5, 10])

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}

petal_length = [label_map[x] for x in bin_petal]

In [37]:
print(petal_length)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

#### 11. Sort the botany dataset based on sepallength column

In [44]:
a = botany_2d[botany_2d[:,0].argsort()]
a

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       ...,
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [7.9, 3.8, 6.4, 2. ]])

#### 12. Find the most frequent value of petal length (3rd column) in botany dataset


In [49]:
value , cunt = np.unique(botany_2d[:,2],return_counts=True)
vals[np.argmax(cunt)]

5.1

#### 13. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of botany dataset


In [53]:
po = np.argwhere(botany_2d[:,3].astype(float)>1.0)[0]
po

array([50], dtype=int64)